package com.nstsolution.forms_v.enumeration;

public enum QuestionType {

    SHORT_QUESTION,
    PARAGRAPH_QUESTION,
    MULTIPLE_CHOICE_QUESTION,
    CHECKBOXES_QUESTIONS,
    DROP_DOWN_LIST_QUESTIONS,
    UPLOAD_FILE_QUESTIONS,
    LINEAR_SCALE_QUESTIONS,
    DATE_QUESTION,
    TIME_QUESTION,
    MULTIPLE_CHOICE_GRID_QUESTIONS,
    CHECKBOXE_GRID_QUESTIONS
}
